name: user-statistician

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Generate user stats image
        uses: cicirello/user-statistician@v1
        with:
          colors: dark
          include-title: false
          image-file: images/userstats.svg
          hide-keys: stars,followers
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
